server.port=0
spring.application.name=mcp-client

# Enable the MCP Client
spring.ai.mcp.client.enabled=true

# Google Gemini Configuration
# spring.ai.google.genai.api-key=<your_key>

# OpenAI Configuration
spring.ai.openai.api-key=<your_key>

# Configure the SSE connection to your WebMVC server
spring.ai.mcp.client.sse.connections.mcp-server.url=http://localhost:8080/mcp
